// <auto-generated />
using System;
using Donation_Platform_For_Education.Infarstructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Donation_Platform_For_Education.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240416070718_CreateDonor&DonationHistory")]
    partial class CreateDonorDonationHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Donation_Platform_For_Education.Domain.Entity.AdminDomain.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("Donation_Platform_For_Education.Domain.Entity.DonorDomain.DonationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("donorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("donorId");

                    b.ToTable("donationHistories");
                });

            modelBuilder.Entity("Donation_Platform_For_Education.Domain.Entity.DonorDomain.Donor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("donors");
                });

            modelBuilder.Entity("Donation_Platform_For_Education.Domain.Entity.AdminDomain.Admin", b =>
                {
                    b.OwnsOne("Donation_Platform_For_Education.Domain.Entity.AdminDomain.AdminContactInfo", "contactInfo", b1 =>
                        {
                            b1.Property<Guid>("AdminId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("phoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AdminId");

                            b1.ToTable("admins");

                            b1.WithOwner()
                                .HasForeignKey("AdminId");
                        });

                    b.Navigation("contactInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Donation_Platform_For_Education.Domain.Entity.DonorDomain.DonationHistory", b =>
                {
                    b.HasOne("Donation_Platform_For_Education.Domain.Entity.DonorDomain.Donor", "donor")
                        .WithMany("donationHistories")
                        .HasForeignKey("donorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("donor");
                });

            modelBuilder.Entity("Donation_Platform_For_Education.Domain.Entity.DonorDomain.Donor", b =>
                {
                    b.Navigation("donationHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
